on:
  push:
    paths:
    - '.github/workflows/**'
    - 'drracket-custom-keybindings/**'
    - 'tests/**'
    - 'kb-base/**'
    - 'info.rkt'
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["CS"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing drracket, rackunit, and framework
        run: raco pkg install --auto base rackunit-lib gui-lib
      - name: Checking racket version and installed libraries
        run: |
          racket -v
          raco pkg show -a
      - name: Installing drracket-custom-keybindings and its dependencies
        run: raco pkg install --no-docs --auto
      - name: Checking installed libraries
        run: raco pkg show -a
      - name: Run tests for the package
        run: raco test -t -p drracket-custom-keybindings